#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 21 14:18:43 2022

@author: vivian
"""

def main ():
    # step one: gather input - an int from the user
    num = int(input("enter an integer\n"))
    
    # step two: calculations (get the ones, tens, and hundreds places)
    hundreds = (num % 1000) // 100
    
    tens = (num % 100) // 10
    
    ones = num % 10
    
    #step three: communication
    print("hundreds", hundreds)
    print("tens", tens)
    print("ones", ones)
    
    
main ()

    